### ISSUE TITLE
I got error when I tried to work with logout

### ISSUE THREAD

**Issue by PhanithNoch** [jkasun/stack-abuse-express-jwt#1]
TypeError: Assignment to constant variable.
    at /Users/tsm168/nodejs-jwt-concept/auth.js:71:19
    at Layer.handle [as handle_request] (/Users/tsm168/nodejs-jwt-concept/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/tsm168/nodejs-jwt-concept/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/tsm168/nodejs-jwt-concept/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/tsm168/nodejs-jwt-concept/node_modules/express/lib/router/layer.js:95:5)
    at /Users/tsm168/nodejs-jwt-concept/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/tsm168/nodejs-jwt-concept/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/tsm168/nodejs-jwt-concept/node_modules/express/lib/router/index.js:275:10)
    at /Users/tsm168/nodejs-jwt-concept/node_modules/body-parser/lib/read.js:130:5

**Comment by NathanielPather** [comment]
>TypeError: Assignment to constant variable.

`const  refreshTokens = [];`
should be
`let  refreshTokens = [];`

constants can't have their values changed after assignment. Further down we are replacing refreshTokens with itself, but with the refresh token removed (empty array).

**Comment by jkasun** [comment]
This is fixed with NathanilePather's pull request.
